//! EML-Runner: исполняет `logic`-секцию контейнера на событиях шины.
//! Состояние = KV-таблица `state` контейнера; логика возвращает ops, которые
//! runner применяет как дельты (append). hal.emit() пишет исходящие .eml в шину.
//!
//! ВНИМАНИЕ: песочницы пока нет — логика контейнера исполняется как есть
//! (python3). Только доверенные контейнеры; sandboxing (seccomp/nsjail) — TODO.

use crate::format::Delta;
use crate::{ipc, kv, reader::EmlBox};
use std::path::Path;
use std::process::Command;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

const HARNESS: &str = r#"# generated by emlbox runner
import json, os, sys
logic_path, event_path, state_path = sys.argv[1], sys.argv[2], sys.argv[3]
bus = os.environ.get("EMLBOX_BUS", "")
entity = os.environ.get("EMLBOX_ENTITY", "unknown")
ev_name = os.environ.get("EMLBOX_EVENT", "EVENT")

ns = {}
with open(logic_path, encoding="utf-8") as f:
    exec(f.read(), ns)

def emit(msg):
    if not bus:
        return
    import time
    to = str(msg.get("to", "system"))
    ev = str(msg.get("event", "EVENT")).replace(" ", "_")
    body = msg.get("data", {})
    name = f"{int(time.time()*1e6)}_{os.getpid()}_{ev}.msg.eml"
    with open(os.path.join(bus, name), "w") as f:
        f.write(f"From: <{entity}@system.local>\r\nTo: <{to}>\r\nX-Event: {ev}\r\n"
                f"X-EMLBox-Msg: v1\r\nContent-Type: application/json\r\n\r\n")
        f.write(json.dumps(body))

with open(event_path) as f:
    event = json.load(f)
if "event" not in event:
    event["event"] = ev_name

with open(state_path) as f:
    state = json.load(f)

fn = ns.get("on_event")
result = fn({"emit": emit}, state, event) if fn else []
if result is None:
    result = []
print(json.dumps(result))
"#;

fn rand_suffix() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0)
}

/// Run the container's logic against bus messages.
/// once=true: process all currently pending messages, then exit.
/// Loop mode: poll until `idle_iters` consecutive idle polls.
pub fn run(container: &Path, bus: &Path, once: bool, idle_iters: u32) -> Result<i32, String> {
    let b = EmlBox::open(container)?;
    let entity = b.entity().ok_or("container has no X-Entity-ID")?;
    let logic = b.section("logic").ok_or("container has no 'logic' section")?;
    let state = kv::table(&b, "state").map_err(|e| format!("state table: {e}"))?;

    let dir = std::env::temp_dir().join(format!("emlbox_run_{}_{}", std::process::id(), rand_suffix()));
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let logic_path = dir.join("logic.py");
    let harness_path = dir.join("harness.py");
    let state_path = dir.join("state.json");
    std::fs::write(&logic_path, logic).map_err(|e| e.to_string())?;
    std::fs::write(&harness_path, HARNESS).map_err(|e| e.to_string())?;
    std::fs::write(&state_path, serde_json::to_vec(&state).map_err(|e| e.to_string())?)
        .map_err(|e| e.to_string())?;

    let mut processed: i32 = 0;
    let mut idle = 0u32;

    loop {
        let msgs = ipc::list(bus)?;
        let mut any = false;
        for m in &msgs {
            let msg = ipc::parse(m)?;
            let to = msg.to.trim_matches(|c| c == '<' || c == '>' || c == ' ');
            if to != entity && to != "*" {
                continue; // belongs to another service — leave pending
            }
            any = true;

            let event_path = dir.join("event.json");
            std::fs::write(&event_path, serde_json::to_vec(&msg.body).map_err(|e| e.to_string())?)
                .map_err(|e| e.to_string())?;
            let out = Command::new("python3")
                .arg(&harness_path)
                .arg(&logic_path)
                .arg(&event_path)
                .arg(&state_path)
                .env("EMLBOX_BUS", bus)
                .env("EMLBOX_ENTITY", &entity)
                .env("EMLBOX_EVENT", &msg.event)
                .output()
                .map_err(|e| format!("python3: {e}"))?;
            if !out.status.success() {
                return Err(format!("logic error: {}", String::from_utf8_lossy(&out.stderr)));
            }
            let ops: Vec<Delta> =
                serde_json::from_slice(&out.stdout).map_err(|e| format!("logic output: {e}"))?;
            for op in &ops {
                match op.op.as_str() {
                    "set" => kv::set(container, &op.table, &op.key, op.value.clone()).map_err(|e| e.to_string())?,
                    "del" => kv::del(container, &op.table, &op.key).map_err(|e| e.to_string())?,
                    other => return Err(format!("logic produced unknown op: {other}")),
                };
            }
            // refresh state snapshot for the next event
            let st = kv::table(&EmlBox::open(container)?, "state").map_err(|e| e.to_string())?;
            std::fs::write(&state_path, serde_json::to_vec(&st).map_err(|e| e.to_string())?)
                .map_err(|e| e.to_string())?;

            println!(
                "[runner] {} <- {} : {} -> {} op(s), state deltas appended",
                entity,
                msg.from.trim_matches(|c| c == '<' || c == '>' || c == ' '),
                msg.event,
                ops.len()
            );
            processed += 1;
            ipc::mark_done(m)?;
        }

        if once {
            break;
        }
        if !any {
            idle += 1;
            if idle >= idle_iters {
                break;
            }
            std::thread::sleep(Duration::from_millis(100));
        }
    }

    let _ = std::fs::remove_dir_all(&dir);
    Ok(processed)
}
